version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env

  web:
    image: nginx:latest
    depends_on:
      - php
      - mysql
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/var/www/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d

  php:
    image: php:7-fpm

volumes:
  mysql_data:
